dist: bionic
language: elixir
elixir: '1.10.4'
otp_release:
  - '22.3'
install:
  - wget https://github.com/rabbitmq/mix_task_archive_deps/releases/download/0.5.0/mix_task_archive_deps-0.5.0.ez
  - mix archive.install --force ./mix_task_archive_deps-0.5.0.ez
script: make tests current_rmq_ref=$TRAVIS_BRANCH
branches:
  only:
    - master
    - v3.7.x
    - v3.8.x
